name: artifacts
on:
  pull_request:
    types:
      - closed
jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: node ./get-token-names.js
      - name: Store token names
        uses: actions/upload-artifact@v3
        with:
          name: tokens
          path: tokens.txt
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - run: doctl app create-deployment --force-rebuild 8214ff44-6a1d-46ce-b764-90158d2b911b