name: Digital Ocean
on:
  pull_request:
    types:
      - closed
jobs:
  deploy_to_do:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: actions/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - run: doctl app create-deployment --force-rebuild 8214ff44-6a1d-46ce-b764-90158d2b911b